#!/bin/bash
# One-click deployment to Render.com

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 DEPLOY CLINICS-FLOW TO RENDER (FREE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Option 1: Quick Deploy (Auto-import)"
echo "--------------------------------"
echo "👉 Click this link to auto-deploy:"
echo ""
echo "   https://render.com/deploy?repo=https://github.com/BasharAlZawahreh/Clinics-Flow"
echo ""
echo "This will:"
echo "  ✅ Connect your GitHub account"
echo "  ✅ Import the Clinics-Flow repository"
echo "  ✅ Use render.yaml configuration"
echo "  ✅ Deploy all services automatically"
echo ""

echo "Option 2: Manual Deploy"
echo "----------------------"
echo "1. Go to: https://dashboard.render.com/register"
echo "2. Create free account"
echo "3. Click: New + → Web Service"
echo "4. Connect GitHub repo: BasharAlZawahreh/Clinics-Flow"
echo "5. Root Directory: . (root)"
echo "6. Build Command: npm install"
echo "7. Start Command: npm start"
echo "8. Click 'Advanced' → Auto-Deploy from Git"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📝 REQUIRED ENVIRONMENT VARIABLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "For Backend Service:"
echo "  DATABASE_URL=postgresql://..."
echo "  JWT_SECRET=<generate-random-string>"
echo "  OPENAI_API_KEY=<your-key>"
echo "  PORT=8080"
echo ""

echo "For Frontend Service:"
echo "  NEXT_PUBLIC_API_URL=https://your-api.onrender.com"
echo "  NODE_ENV=production"
echo ""

echo "Generate JWT_SECRET:"
echo "  node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⏱️  DEPLOYMENT TIME"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  First deployment: 5-10 minutes"
echo "  Subsequent deploys: 2-3 minutes (on git push)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🌐 YOUR DEPLOYED URLs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Frontend: https://clinics-flow-web.onrender.com"
echo "  API:      https://clinics-flow-api.onrender.com"
echo "  Dashboard: https://dashboard.render.com"
echo ""

echo "💡 TIPS:"
echo "  - Free tier spins down after 15 min inactivity"
echo "  - First cold start takes ~30 seconds"
echo "  - Database stays active (no spin down)"
echo "  - Monitor logs in Render dashboard"
echo ""
echo "❓ Need help? Check: REACT_DEPLOYMENT.md"
echo ""
